import pandas as pd

from domain.portfolio import Portfolio
from data import InstrumentFactory


class PortfolioLoader:
    '''
    Responsible for composing portfolio from various sources.
    '''

    def __init__(self, instrument_factory: InstrumentFactory):
        if instrument_factory is None:
            raise ValueError('Instrument factory must be provided.')
        self.factory = instrument_factory


    def from_csv(
            self,
            path: str,
            name: str | None = None
        ) -> Portfolio:
        '''
        Load portfolio from CSV-file generated by the SDFI trading system.
        '''

        df = pd.read_csv(path, dtype=str)
        df = self._global_cleanup(df)

        contracts = list()
        for _, row in df.iterrows():
            contract = self.factory.from_row(row.to_dict())
            contracts.append(contract)

        return Portfolio(contracts=contracts, name=name)


    @staticmethod
    def _global_cleanup(df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()

        # Drop unused columns (errors='ignore' for some CSVs are subsets of the full format)
        df.drop(
            columns=[
                'Номер в клиринговой системе',
                'Номер в торговой системе',
                'Владелец',
                'Клиент',
                'Сторона парного договора',
                'Стоимость',
                'CSA',
                'Наименование стороны парного договора',
                'Время регистрации',
                'Счет',
                'Пользователь',
                'Комментарий',
                'Статус',
                'Режим торгов',
                'Брокер',
                'Комиссии',
                'Контрагент'
            ],
            errors='ignore',
            inplace=True
        )

        # Rename columns
        df.rename(
            columns={
                'Дата регистрации': 'registration_date',
                'Продукт': 'product',
                'Инструмент': 'name',
                'Направление': 'direction',
                'Цена': 'price',
                'Курс': 'rate',
                'Срок': 'maturity',
                'Начало': 'start_date',
                'Окончание': 'end_date',
                'Сумма 1': 'amount_1',
                'Валюта 1': 'currency_1',
                'Сумма 2': 'amount_2',
                'Валюта 2': 'currency_2',
                'Маржа': 'margin',
                'Ордер': 'order',
                'Сумма премии': 'premium',
                'Дата премии': 'premium_date',
                'Валюта премии': 'premium_currency',
                'Страйк': 'strike'
            },
            inplace=True
        )

        return df

